### PR TITLE
Added LICENSE file

### PR DESCRIPTION
**Pull request by marcodejongh**
I really want to use your module, but I can't without a license.

### CODE REVIEW

**Comment by michaelmelanson** [comment]
@dscape Any chance of getting this merged? This is sticking out like a sore thumb in our license checking reports.

**Comment by graingert** [comment]
The current license,

```js
Public Domain.

NO WARRANTY EXPRESSED OR IMPLIED. USE AT YOUR OWN RISK.

This code should be minified before deployment.
See http://javascript.crockford.com/jsmin.html

USE YOUR OWN COPY. IT IS EXTREMELY UNWISE TO LOAD CODE FROM SERVERS YOU DO
NOT CONTROL.
```

Is not valid, as a work cannot be placed into the public domain, it can only lapse into the public domain. Thus, you cannot convert it to the MIT license.

The best you can do is tag it accordingly https://github.com/dscape/cycle/pull/13 and let other uses decide how they want to use the code.

**Comment by graingert** [comment]
@douglascrockford any chance of co-licensing https://github.com/douglascrockford/JSON-js under MIT or Apache 2

**Comment by dscape** [comment]
Sorry this is not going to happen, it's licensed as the original author wanted it to be. It's his work mostly, and won't be changed by anyone else than him.

**Comment by graingert** [comment]
@dscape can you leave this open until we get a response from @douglascrockford

**Pull request closed without merging**
